### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by hammackj** [abenson/minitalk#2]
If you type something out and press enter, then type something new the cursor fucks all the things.

**Comment by abenson** [comment]
I'll need a better description.

**Comment by hammackj** [comment]
Here is a video.
![cursor_fucks](https://cloud.githubusercontent.com/assets/172781/11316581/84834d0c-8fd2-11e5-8e15-e63cce6254b6.gif)

**Comment by abenson** [comment]
Unable to recreate on readline 6.3. Will test further.

Here is a video.
[image: cursor_fucks]
https://cloud.githubusercontent.com/assets/172781/11316581/84834d0c-8fd2-11e5-8e15-e63cce6254b6.gif

**Comment by abenson** [comment]
This was an issue from a pre-release version.
